on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'test git action'
        run: pwd

      - name: 'test git action'
        run: pwd  






